spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8081
          predicates:
            - Path=/customer/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/product/**
        - id: cart-service
          uri: http://localhost:8083
          predicates:
            - Path=/cart/**