spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/analytics/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/